import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "kFE4cC7NnG481HmXKTKA4Odlf_MYIpuoLN6HCqpDl0g",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Properly placed meta tag //*/}
        <meta
          name="google-site-verification"
          content="kFE4cC7NnG481HmXKTKA4Odlf_MYIpuoLN6HCqpDl0g"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
